---
title: "Station Report"

output: pdf_document 

params: 

  startdate: NA
  enddate: NA
  months: NA
  station: NA
  samples: NA
  chosensample: NA
  gm: NA 
  stv: NA
  station_num: NA
  data: NA
  name: NA


  
---
```{r, echo=FALSE}
library(ggplot2)
library(tidyverse)
# library(knitr)
# library(kableExtra)
library(dplyr)

```


```{r, echo=FALSE}
# months that are selected 


selected_month <- if(length(params$months)==12){
                      'All'
                  }else{
                    params$months
                    }
```


**Station ID:**   `r params$station`  
**Station Name:**   `r params$name`  
**Date Range:**      `r params$startdate` - `r params$enddate`  
**Months:**     `r selected_month`  
**Minimum number of samples taken each year:**     `r params$chosensample`
**Total Number of Samples:**     `r params$samples`  
**Station E. coli Geomean (CFU/100 ml):**    `r params$gm`  
**Station E. coli STV (CFU/100 ml):**        `r params$stv`  


```{r, echo=FALSE}
data <- params$data %>%
            filter(station_num == params$station_num) %>% 
            ungroup() %>% 
            # select(HUC8, ActivityIdentifier, date, ReportedEcoli, DetectionValue, DetectionType, Ecoli, lat, lon)%>%
            arrange(date)

data %>%
  ggplot(aes(x = date, y= Ecoli)) +
  geom_point() + 
  labs(x = "Date", y= "E. coli (CFU/100 ml)")


```

```{r, echo=FALSE,  results='asis'}

# 
# data_table <- data %>% select(ActivityIdentifier, 
#                                Date = date, 
#                                ReportedEcoli, 
#                                DetectionValue, 
#                                DetectionType, 
#                                Ecoli,
#                                lat,  
#                                lon)
# 
# data_table %>% 
#   kable(format = "pandoc", escape = F, caption ="Station Data Contributing to Calculations and Scatterplot") 
#                 

```